## @section Squid Proxy Configuration

global:
  ## @param global.resourceTier Resource deployment type
  resourceTier: "medium"
  ## @param global.imagePullSecrets [array] Existing truefoundry image pull secret name
  imagePullSecrets: []
  ## @param global.truefoundryImagePullConfigJSON Truefoundry image pull secret JSON
  truefoundryImagePullConfigJSON: ""
  ## @param global.affinity [object] Affinity rules for pod scheduling on a node
  affinity: {}
  ## @param global.labels [object] Global labels
  labels: {}
  ## @param global.annotations [object] Global annotations
  annotations: {}
  ## @param global.podLabels [object] Global pod labels
  podLabels: {}
  ## @param global.podAnnotations [object] Global pod annotations
  podAnnotations: {}
  ## @param global.deploymentLabels [object] Global deployment labels
  deploymentLabels: {}
  ## @param global.deploymentAnnotations [object] Global deployment annotations
  deploymentAnnotations: {}
  ## @param global.serviceAnnotations [object] Global service annotations
  serviceAnnotations: {}
  ## @param global.serviceLabels [object] Global service labels
  serviceLabels: {}
  ## @param global.tolerations [array] Tolerations for pod scheduling on a node
  tolerations: []
  ## @param global.nodeSelector [object] Node selector
  nodeSelector: {}

  ## @param global.image.registry Global image registry override
  image:
    registry: "tfy.jfrog.io"
  ## @param global.namespaceOverride Namespace override (defaults to .Release.Namespace if not set)
  namespaceOverride: ""

## @param fullnameOverride Full name override for the tfy-squid-proxy
fullnameOverride: ""
## @param nameOverride Name override
nameOverride: ""

## @param replicas Number of replicas of squid proxy service
replicas: 3
## @param commonLabels Common labels
commonLabels: {}
## @param commonAnnotations Common annotations
commonAnnotations: {}
## @param podLabels Pod labels
podLabels: {}
## @param podAnnotations Pod annotations
podAnnotations: {}
## @param deploymentLabels Deployment labels
deploymentLabels: {}
## @param deploymentAnnotations Deployment annotations
deploymentAnnotations: {}
## Image configuration for squid proxy
image:
  ## @param image.registry Image registry for squid proxy
  registry: ""
  ## @param image.repository Image repository for squid proxy
  repository: tfy-mirror/ubuntu/squid
  ## @param image.tag Image tag for squid proxy
  tag: "6.6-24.04_edge"
  ## @param image.pullPolicy Image pull policy
  pullPolicy: IfNotPresent

## @param imagePullSecrets [array] Image pull secrets
imagePullSecrets: []

## Service configuration
service:
  ## @param service.type Service type
  type: ClusterIP
  ## @param service.port Service port
  port: 3128
  ## @param service.annotations Service annotations
  annotations: {}
  ## @param service.labels Service labels
  labels: {}

## @skip config Squid configuration file content
config: |
  # ------------------------
  # Listens on 3128
  # ------------------------
  http_port 3128

  # No caching
  cache deny all

  # Allow all by default
  http_access allow all

## @skip replicaCount Number of replicas
# replicaCount: 1

## Autoscaling configuration
autoscaling:
  ## @param autoscaling.enabled Enable autoscaling
  enabled: false
  ## @param autoscaling.minReplicas Minimum number of replicas
  minReplicas: 3
  ## @param autoscaling.maxReplicas Maximum number of replicas
  maxReplicas: 100
  ## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
  targetCPUUtilizationPercentage: 60

## @param tolerations [array] Tolerations
tolerations: []

## @param affinity [object] Affinity
affinity: {}

## @param nodeSelector [object] Node selector
nodeSelector: {}

## @param containerSecurityContext [object] Container Security Context
containerSecurityContext: {}

## @param podSecurityContext [object] Pod Security Context
podSecurityContext: {}
