apiVersion: v2
name: tfy-k8s-gcp-gke-standard-inframold
version: 0.1.189
description: "Inframold, the superchart that configure your cluster on gcp for truefoundry."
maintainers:
  - name: truefoundry
