tenantName: <tenant_name>
clusterName: <cluster_name>
argocd:
  enabled: true
argoWorkflows:
  enabled: true
argoRollouts:
  enabled: false
notebookController:
  enabled: false
aws:
  awsLoadBalancerController:
    enabled: false
  karpenter:
    enabled: false
  awsEbsCsiDriver:
    enabled: false
  awsEfsCsiDriver:
    enabled: false
gpu:
  enabled: false
truefoundry:
  enabled: true
  truefoundryBootstrap:
    enabled: true
  tfyApiKey: <tfy_api_key>
  truefoundryImagePullConfigJSON: <truefoundry_image_pull_config_json>
  devMode:
    enabled: true
  servicefoundryServer:
    env:
      INTERNAL_JWT_JWKS: <truefoundry_internal_jwt_jwks>
      OAUTH_PROVIDER_TYPE: "INITIAL_ADMIN"
      INTERNAL_JWT_SERVICE_ENABLED: "true"
      INITIAL_ADMIN_OAUTH_USER_PASSWORD: <initial_admin_oauth_user_password>
loki:
  enabled: true
istio:
  enabled: false
keda:
  enabled: false
kubecost:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
tfyAgent:
  enabled: false
elasti:
  enabled: false
