apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ml-ctc-america-cert
  namespace: istio-system
spec:
  dnsNames:
    - ml.ctc-america.truefoundry.cloud
    - '*.ml.ctc-america.truefoundry.cloud'
  duration: 2160h
  issuerRef:
    name: letsencrypt-issuer
  renewBefore: 360h
  secretName: ml-ctc-america-tls
