{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tfy-istio-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    truefoundry.com/infra-component: "tfy-istio-ingress"
  annotations:
    helm.sh/hook: post-install
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    chart: tfy-istio-ingress
    repoURL: https://truefoundry.github.io/infra-charts/
    targetRevision: 0.3.2
    helm:
      values: |-
        {{- if .Values.istio.gateway.valuesOverride }}
        {{ .Values.istio.gateway.valuesOverride | toYaml | nindent 8 }}
        {{- else }}
        {{- $mergedTolerations := .Values.tolerations }}
        {{- if .Values.istio.gateway.tolerations }}
        {{- $mergedTolerations = .Values.istio.gateway.tolerations }}
        {{- end }}

        {{- $mergedAffinity := .Values.affinity }}
        {{- if .Values.istio.gateway.affinity }}
        {{- $mergedAffinity = .Values.istio.gateway.affinity }}
        {{- end }}
        gateway:
          {{- with .Values.istio.gateway.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 10 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 12 }}
          {{- end }}
        tfyGateway:
          name: 'tfy-wildcard'
          spec:
            selector:
              istio: 'tfy-istio-ingress'
            servers:
              - hosts:
                {{- range .Values.istio.tfyGateway.domains }}
                - {{ . | quote}}
                {{- end }}
                port:
                  name: http-tfy-wildcard
                  number: 80
                  protocol: HTTP
                tls:
                  httpsRedirect: {{ .Values.istio.tfyGateway.httpsRedirect }}
              - hosts:
                {{- range .Values.istio.tfyGateway.domains }}
                - {{ . | quote}}
                {{- end }}
                {{- if .Values.istio.tfyGateway.tls.enabled }}
                port:
                  name: https-tfy-wildcard
                  number: 443
                  protocol: HTTPS
                tls:
                  mode: {{ .Values.istio.tfyGateway.tls.mode }}
                  credentialName: {{ .Values.istio.tfyGateway.tls.credentialName }}
                {{- else }}
                port:
                  name: https-tfy-wildcard
                  number: 443
                  protocol: HTTP
                {{- end }}
        {{- end }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
