{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-discovery
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
  labels:
    truefoundry.com/infra-component: "istio-discovery"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.2
    helm:
      values: |-
        {{- if .Values.istio.discovery.valuesOverride }}
        {{ .Values.istio.discovery.valuesOverride | toYaml | nindent 8 }}
        {{- else }}
        {{- $mergedTolerations := .Values.tolerations }}
        {{- if .Values.istio.tolerations }}
        {{- $mergedTolerations = .Values.istio.tolerations }}
        {{- end }}

        {{- $mergedAffinity := .Values.affinity }}
        {{- if .Values.istio.affinity }}
        {{- $mergedAffinity = .Values.istio.affinity }}
        {{- end }}
        pilot:          
          autoscaleEnabled: true
          autoscaleMin: 2
          replicaCount: 2
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
              ephemeral-storage: 512Mi
            limits:
              cpu: 400m
              memory: 1024Mi
              ephemeral-storage: 1024Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 14 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 14 }}
          {{- end }}
        global:
          {{- if .Values.registry }}
          hub: {{ .Values.registry }}/istio-release
          {{- end }}
          {{- range .Values.imagePullSecrets }}
          imagePullSecrets:
            - {{ .name }}
          {{- end }}
          {{- if .Values.istio.discovery.hub }}
          hub: {{ .Values.istio.discovery.hub }}
          {{- end }}
          {{- if .Values.istio.discovery.tag }}
          tag: {{ .Values.istio.discovery.tag }}
          {{- end }}
        {{- end }}

  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
