apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  issuerRef:
    name: {{ .Values.issuer.name }}
  dnsNames:
    {{- range .Values.certificate.domain_names }}
    - {{ . }}
    {{- end }}

