{{- range $key, $issuer := .Values.issuers }}
{{- $issuerName := $issuer.name }}
{{- with $issuer.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
spec:
  secretName: {{ .secretName }}
  duration: {{ .duration | default "2160h" }}
  renewBefore: {{ .renewBefore | default "360h" }}
  issuerRef:
    name: {{ $issuerName }}
  dnsNames:
    {{- range .domains }}
    - {{ . | quote }}
    {{- end }}
---
{{- end }}
{{- end }}