apiVersion: v2
appVersion: 1.2.0
description: A Helm chart for eks-node-montoring-agent
home: https://github.com/aws/eks-node-monitoring-agent
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
  - eks
name: eks-node-monitoring-agent
sources:
  - https://github.com/aws/eks-node-monitoring-agent
version: 1.5.1
