apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfy-squid-proxy.fullname" . }}-squid-proxy
  labels:
    {{- include "tfy-squid-proxy.deploymentLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-squid-proxy.deploymentAnnotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ include "tfy-squid-proxy.replicas" . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tfy-squid-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tfy-squid-proxy.podLabels" . | nindent 8 }}
      annotations:
        {{- include "tfy-squid-proxy.podAnnotations" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "tfy-squid-proxy.imagePullSecrets" . | nindent 8 }}
      nodeSelector:
        {{- include "tfy-squid-proxy.nodeSelector" . | nindent 8 }}
      affinity:
        {{- include "tfy-squid-proxy.affinity" . | nindent 8 }}
      tolerations:
        {{- include "tfy-squid-proxy.tolerations" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry | default .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/sbin/squid"]
          args: ["-N", "-f", "/etc/squid/squid.conf"]
          ports:
            - name: proxy
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
          resources:
            {{- include "tfy-squid-proxy.resources" . | nindent 12 }}
          securityContext:
            {{- include "tfy-squid-proxy.containerSecurityContext" . | nindent 12 }}
      volumes:
        - name: squid-config
          configMap:
            name: {{ include "tfy-squid-proxy.fullname" . }}-squid-proxy-config
      securityContext:
        {{- include "tfy-squid-proxy.podSecurityContext" . | nindent 8 }}
