apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfy-squid-proxy.fullname" . }}
  labels:
    {{- include "tfy-squid-proxy.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-squid-proxy.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "tfy-squid-proxy.selectorLabels" . | nindent 4 }}

