{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    truefoundry.com/infra-component: "cert-manager"
  annotations:
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.2
    helm:
      values: |-
        {{- if .Values.certManager.valuesOverride }}
        {{ .Values.certManager.valuesOverride | toYaml | nindent 8 }}
        {{- else }}
        {{- $mergedTolerations := .Values.tolerations }}
        {{- if .Values.certManager.tolerations }}
        {{- $mergedTolerations = .Values.certManager.tolerations }}
        {{- end }}

        {{- $mergedAffinity := .Values.affinity }}
        {{- if .Values.certManager.affinity }}
        {{- $mergedAffinity = .Values.certManager.affinity }}
        {{- end }}
        extraArgs:
        - --issuer-ambient-credentials
        podLabels:
          {{- toYaml .Values.certManager.podLabels | nindent 10 }}
        serviceAccount:
          create: true
          labels:
            {{- toYaml .Values.certManager.podLabels | nindent 12 }}
        crds:
          enabled: true
        {{- if $mergedTolerations }}
        tolerations:
          {{- toYaml $mergedTolerations | nindent 10 }}
        {{- end }}
        {{- if $mergedAffinity }}
        affinity:
          {{- toYaml $mergedAffinity | nindent 10 }}
        {{- end }}
        webhook:
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 256Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 10 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 12 }}
          {{- end }}
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
            ephemeral-storage: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: 256Mi
        cainjector:
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 256Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 10 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 12 }}
          {{- end }}
        startupapicheck:
          enabled: true
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 10 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 12 }}
          {{- end }}
        prometheus:
          servicemonitor:
            enabled: true
            labels:
              release: prometheus
        {{- end }}
  syncPolicy:
    automated: {}
    retry: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
