{{- if .Values.sparkOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    truefoundry.com/infra-component: "spark-operator"
  annotations:
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
spec:
  destination:
    namespace: spark-operator
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    targetRevision: 2.2.1
    repoURL: "https://kubeflow.github.io/spark-operator"
    chart: spark-operator
    helm:
      values: |-
        {{- if .Values.sparkOperator.valuesOverride }}
        {{ .Values.sparkOperator.valuesOverride | toYaml | nindent 8 }}
        {{- else }}
        {{- $mergedTolerations := .Values.tolerations }}
        {{- if .Values.sparkOperator.tolerations }}
        {{- $mergedTolerations = .Values.sparkOperator.tolerations }}
        {{- end }}

        {{- $mergedAffinity := .Values.affinity }}
        {{- if .Values.sparkOperator.affinity }}
        {{- $mergedAffinity = .Values.sparkOperator.affinity }}
        {{- end }}
        {{- if or .Values.registry .Values.imagePullSecrets }}
        image:
          {{- if .Values.registry }}
          registry: {{ .Values.registry }}
          {{- end }}
          {{- if .Values.imagePullSecrets }}
          pullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          {{- end }}
        controller:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
              ephemeral-storage: 512Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 14 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 14 }}
          {{- end }}
        webhook:
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 14 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 14 }}
          {{- end }}
        spark:
          jobNamespaces:
            - ""
        {{- if $mergedTolerations }}
        tolerations:
          {{- toYaml $mergedTolerations | nindent 14 }}
        {{- end }}
        {{- if $mergedAffinity }}
        affinity:
          {{- toYaml $mergedAffinity | nindent 14 }}
        {{- end }}
      {{- end }}
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
