{{- if .Values.jspolicy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jspolicy-config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    truefoundry.com/infra-component: "tfy-jspolicy-config"
  annotations:
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
spec:
  destination:
    namespace: jspolicy
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    chart: tfy-jspolicy-config
    repoURL: "https://truefoundry.github.io/infra-charts/"
    targetRevision: 0.2.4
    helm:
      {{- if .Values.jspolicy.config.valuesOverride }}
      values: |-
      {{ .Values.jspolicy.config.valuesOverride | toYaml | nindent 8 }}
      {{- else }}
      values: ""
      {{- end }}
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
