{{- if .Values.gpu.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tfy-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    truefoundry.com/infra-component: "tfy-gpu-operator"
  annotations:
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
spec:
  destination:
    namespace: tfy-gpu-operator
    server: https://kubernetes.default.svc
  project: tfy-apps
  source:
    repoURL: https://truefoundry.github.io/infra-charts/
    chart: tfy-gpu-operator
    targetRevision: 0.4.5
    helm:
      values: |-
        {{- if .Values.gpu.valuesOverride }}
        {{ .Values.gpu.valuesOverride | toYaml | nindent 8 }}
        {{- else }}
        clusterType:
          {{.Values.gpu.clusterType}}: true
        {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true
{{- end }}
