{{- if .Values.global.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "truefoundry.virtualservice.fullname" . }}
  labels:
    {{- include "truefoundry.virtualservice.labels" . | nindent 4 }}
  annotations:
    {{- include "truefoundry.virtualservice.annotations" . | nindent 4 }}
spec:
  gateways:
  {{- range .Values.global.virtualservice.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.global.virtualservice.hosts }}
    - {{ . }}
  {{- end }}
  {{- if $.Values.global.proxy.enabled }}
  http:
    - match:
        - uri:
            prefix: "/flyteidl.service.AdminService/"
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.tfyWorkflowAdminHost . }}
            port:
              number: 8089
          weight: 100
    - route:
        - destination:
            host: {{ tpl .Values.global.proxy.tfyProxyHost . }}
            port:
              number: 8080
  {{- else }}
  http:
    - match:
        - uri:
            prefix: "/api/svc/socket.io"
      rewrite:
        uri: /socket.io
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.servicefoundryServerHost . }}
            port:
              number: 3000
    - match:
        - uri:
            prefix: "/api/llm/"
      rewrite:
        uri: /
      {{- if .Values.global.proxy.llmGateway.external }}
        authority: {{ tpl .Values.global.proxy.llmGateway.backendHost . }}
      {{- end }}
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.llmGateway.backendHost . }}
            port:
              number: {{ .Values.global.proxy.llmGateway.backendPort }}
    - match:
        - uri:
            prefix: /api/proxy-server/
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.proxyServerHost . }}
            port:
              number: 8123
    - match:
        - uri:
            prefix: "/flyteidl.service.AdminService/"
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.tfyWorkflowAdminHost . }}
            port:
              number: 8089
          weight: 100
    - match:
        - uri:
            prefix: "/api/s3proxy/"
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.s3proxyHost . }}
            port:
              number: {{ .Values.s3proxy.service.port }}
    - match:
        - uri:
            prefix: "/api/otel/"
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ tpl .Values.global.proxy.tfyOtelCollector.host . }}
            port:
              number: 4318
    - route:
        - destination:
            host: {{ tpl .Values.global.proxy.truefoundryFrontendAppHost . }}
            port:
              number: 5000
  {{- end }}
{{- end }}
