apiVersion: v2
name: tfy-logs
description: Truefoundry Logs chart
version: 0.1.15
maintainers:
  - name: truefoundry
dependencies:
  - name: victoria-logs-single
    version: 0.11.19
    repository: https://victoriametrics.github.io/helm-charts/
