{{- if .Values.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    truefoundry.com/infra-component: "prometheus"
  annotations:
    helm.sh/resource-policy: {{ .Values.helm.resourcePolicy }}
spec:
  project: tfy-apps
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 81.2.0
    chart: kube-prometheus-stack
    helm:
      values: |-
        {{- if .Values.prometheus.valuesOverride }}
        {{ .Values.prometheus.valuesOverride | toYaml | nindent 8 }}
        {{- else }}
        {{- $mergedTolerations := .Values.tolerations }}
        {{- if .Values.prometheus.tolerations }}
        {{- $mergedTolerations = .Values.prometheus.tolerations }}
        {{- end }}

        {{- $mergedAffinity := .Values.affinity }}
        {{- if .Values.prometheus.affinity }}
        {{- $mergedAffinity = .Values.prometheus.affinity }}
        {{- end }}
        {{- if or .Values.registry .Values.imagePullSecrets }}
        global:
          {{- if .Values.registry }}
          imageRegistry: {{ .Values.registry }}
          {{- end }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
        {{- end }}
        crds:
          enabled: true
          upgradeJob:
            image:
              busybox:
                registry: tfy.jfrog.io/tfy-mirror
            enabled: true # will be removed once it is upgraded everywhere
            forceConflicts: true # will be removed once it is upgraded everywhere
        defaultRules:
          enabled: false
        coreDns:
          enabled: false
        grafana:
          enabled: false
        kubelet:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeProxy:
          enabled: false
        kubernetesServiceMonitors:
          enabled: false
        prometheus:
          prometheusSpec:
            resources:
              limits:
                cpu: "3.8"
                memory: 10Gi
              requests:
                cpu: "1.9"
                memory: 2Gi
            retention: 30d
            containers:
            - livenessProbe:
                failureThreshold: 10
                initialDelaySeconds: 60
                periodSeconds: 10
                timeoutSeconds: 10
              name: prometheus
              readinessProbe:
                failureThreshold: 10
                initialDelaySeconds: 60
                periodSeconds: 10
                timeoutSeconds: 10
              startupProbe:
                failureThreshold: 10
                initialDelaySeconds: 300
                periodSeconds: 10
                timeoutSeconds: 10
            - name: config-reloader
              resources:
                requests:
                  cpu: 10m
                  memory: 20Mi
                limits:
                  cpu: 20m
                  memory: 40Mi
            initContainers:
            - name: init-config-reloader
              resources:
                requests:
                  cpu: 10m
                  memory: 20Mi
                limits:
                  cpu: 20m
                  memory: 40Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 20Gi
                  accessModes:
                    - ReadWriteOnce
            retentionSize: 18GB
            enableAdminAPI: true
            {{- if $mergedTolerations }}
            tolerations:
              {{- toYaml $mergedTolerations | nindent 14 }}
            {{- end }}
            {{- if $mergedAffinity }}
            affinity:
              {{- toYaml $mergedAffinity | nindent 14 }}
            {{- end }}
            additionalScrapeConfigs: []
          serviceMonitor:
            selfMonitor: false
        alertmanager:
          alertmanagerSpec:
            alertmanagerConfigMatcherStrategy:
              type: None
            containers:
            - name: config-reloader
              resources:
                requests:
                  cpu: 10m
                  memory: 20Mi
                limits:
                  cpu: 20m
                  memory: 40Mi
            initContainers:
            - name: init-config-reloader
              resources:
                requests:
                  cpu: 10m
                  memory: 20Mi
                limits:
                  cpu: 20m
                  memory: 40Mi
            resources:
              requests:
                cpu: 200m
                memory: 240Mi
                ephemeral-storage: 128Mi
              limits:
                cpu: 400m
                memory: 480Mi
                ephemeral-storage: 256Mi
          enabled: true
          serviceMonitor:
            selfMonitor: false
        kubeApiServer:
          enabled: false
        kubeScheduler:
          enabled: false
        kube-state-metrics:
          resources:
            limits:
              cpu: 200m
              memory: 330Mi
              ephemeral-storage: 256Mi
            requests:
              cpu: 100m
              memory: 170Mi
              ephemeral-storage: 256Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 12 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 12 }}
          {{- end }}
          prometheus:
            monitor:
              enabled: false
          metricLabelsAllowlist:
            - pods=[truefoundry.com/application,truefoundry.com/component-type,truefoundry.com/component,truefoundry.com/application-id]
            - nodes=[karpenter.sh/capacity-type,karpenter.sh/nodepool,karpenter.sh/nodeclaim,eks.amazonaws.com/capacityType,kubernetes.azure.com/scalesetpriority,kubernetes.azure.com/accelerator,cloud.google.com/gke-provisioning,node.kubernetes.io/instance-type]
        prometheusOperator:
          resources:
            limits:
              cpu: 400m
              memory: 200Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 200m
              memory: 100Mi
              ephemeral-storage: 256Mi
          {{- if $mergedTolerations }}
          tolerations:
            {{- toYaml $mergedTolerations | nindent 12 }}
          {{- end }}
          {{- if $mergedAffinity }}
          affinity:
            {{- toYaml $mergedAffinity | nindent 12 }}
          {{- end }}
          admissionWebhooks:
            patch:
              enabled: true
              {{- with .Values.tolerations }}
              tolerations:
                {{ toYaml . | nindent 14 }}
              {{- end }}
              {{- with .Values.affinity }}
              affinity:
                {{ toYaml . | nindent 14 }}
              {{- end }}
              resources:
                requests:
                  cpu: 50m
                  memory: 40Mi
                limits:
                  cpu: 100m
                  memory: 400Mi
          serviceMonitor:
            selfMonitor: false
        kubeControllerManager:
          enabled: false
        prometheus-node-exporter:
          extraArgs:
            - --web.disable-exporter-metrics
            - --collector.disable-defaults
            - --collector.cpu
            - --collector.meminfo
            - --collector.filesystem
            - --collector.stat
            - --collector.pressure
            - --collector.loadavg
            - --collector.time
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
            - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
          resources:
            limits:
              cpu: 200m
              memory: 80Mi
            requests:
              cpu: 100m
              memory: 40Mi
          prometheus:
            monitor:
              enabled: false
        prometheusConfigReloader:
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 200m
              memory: 80Mi
              ephemeral-storage: 256Mi
        additionalPrometheusRulesMap: {}
        {{- end }}
{{- end }}
