apiVersion: v2
name: tfy-grafana
description: Truefoundry grafana provisioner
version: 0.1.19
maintainers:
  - name: truefoundry
dependencies:
  - name: grafana
    version: 9.2.10
    repository: "https://grafana.github.io/helm-charts"
