apiVersion: v2
name: tfy-grafana
description: Truefoundry grafana provisioner
version: 0.1.21
maintainers:
  - name: truefoundry
dependencies:
  - name: grafana
    version: 10.4.0
    repository: "https://grafana.github.io/helm-charts"
