{{- if .Values.awsElbControllerChecker.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-elb-controller-checker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-elb-controller-checker.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-elb-controller-checker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-elb-controller-checker.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
