{{- if and .Values.awsElbControllerChecker.enabled .Values.awsElbControllerChecker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-elb-controller-checker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "aws-elb-controller-checker.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
