{{- if and .Values.awsElbControllerChecker.enabled .Values.awsElbControllerChecker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-elb-controller-checker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-elb-controller-checker.labels" . | nindent 4 }}
  annotations:
    {{- include "aws-elb-controller-checker.annotations" . | nindent 4 }}
{{- end }}
