apiVersion: v2
name: tfy-istio-ingress
version: 0.1.1
description: "ArgoCD Applications for istio ingress config"
maintainers:
  - name: truefoundry
dependencies:
  - name: gateway
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.20.1
