apiVersion: v2
name: tfy-istio-ingress
version: 0.3.4
description: "ArgoCD Applications for istio ingress config"
maintainers:
  - name: truefoundry
dependencies:
  - name: gateway
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.28.1
  - name: tfy-gateway-api-crd
    version: 0.1.0
    repository: https://truefoundry.github.io/infra-charts/
