{{- if and .Values.tfyProxy.enabled .Values.tfyProxy.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tfy-proxy.fullname" . }}
  labels:
    {{- include "tfy-proxy.serviceMonitorLabels" . | nindent 4 }}
  annotations:
    {{- include "tfy-proxy.serviceMonitorAnnotations" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "global.namespace" . }}
  selector:
    matchLabels:
      {{- include "truefoundry.selectorLabels" (dict "context" . "name" "tfy-proxy") | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.tfyProxy.serviceMonitor.path }}
      honorLabels: true
      interval: {{ .Values.tfyProxy.serviceMonitor.interval }}
{{- end -}}