apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: notebook-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notebook-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: notebook-controller-service-account
    namespace: {{ tpl .Values.namespace . }}
