apiVersion: v2
name: tfy-gateway-api-crd
description: Helm chart for the Gateway API CRDs
type: application
version: 0.1.1
# Upstream CRD version https://github.com/kubernetes-sigs/gateway-api/releases
appVersion: "1.4.0"
maintainers:
- name: truefoundry
